version: '2'
services:
  db:
    image: mariadb:10.1
    environment:
      - MYSQL_ROOT_PASSWORD=randompassword
      - MYSQL_DATABASE=ipeer
      - MYSQL_USER=ipeer
      - MYSQL_PASSWORD=ipeer
    volumes:
      - ./.data:/var/lib/mysql
  app:
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    environment:
      - IPEER_DB_HOST=db
      - IPEER_DB_USER=ipeer
      - IPEER_DB_PASSWORD=ipeer
      - IPEER_DEBUG=2
      - IPEER_SESSION_SAVE=database
    depends_on:
      - db
  web:
    image: nginx:1.11
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./app/webroot:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - app
